import paho.mqtt.client as PahoMQTT
import requests
import json
import threading

# Class to subscribe to the temperature data generated by the Yun
class MQTTTemperatureReceiver:
    def __init__(self, catalogURL: str, catalogPORT: str, deviceID: str, period: float):
        self.catalogURL = catalogURL
        self.catalogPORT = catalogPORT
        self.deviceID = deviceID

        # Get the mqtt broker from the catalog
        try:
            response = requests.get(self.catalogURL + ":" + str(self.catalogPORT) + "/getMQTTMessageBroker")
            response.raise_for_status()
        except:
            raise ConnectionError("Unable to get mqtt broker from the catalog")

        try:
            responseDict = json.loads(response.text)
            if "url" not in responseDict or "port" not in responseDict:
                raise Exception()
        except:
            raise Exception("Response from catalog was invalid")

        self.brokerURL = responseDict["url"]
        self.brokerPORT = responseDict["port"]

        # Get the devices registered to the catalog
        try:
            response = requests.get(self.catalogURL + ":" + str(self.catalogPORT) + "/getDevices")
            response.raise_for_status()
        except:
            raise ConnectionError("Unable to get list of devices from the catalog")

        try:
            responseDict = json.loads(response.text)
        except:
            raise Exception("Response from catalog was invalid")

        # Search the desired device in the response
        found = False
        
        for d in responseDict:
            if "deviceID" in d and d["deviceID"] == self.deviceID:
                found = True
                device = d
                break
        
        if not found:
            raise Exception("Desired device '" + self.deviceID + "' not found in catalog")

        # Find the end point corresponding to the resource we want to listen to (temperature)
        try:
            if "resources" not in device or "endPoints" not in device or len(device["resources"]) != len(device["endPoints"]):
                raise Exception
            temperatureResourceIndex = device["resources"].index("temperature")
        except:
            raise Exception("Device descriptor is incomplete")

        endPoint = device["endPoints"][temperatureResourceIndex] # This should be the end point we're interested in

        # We expect an mqtt topic set as 'publisher'
        if "service" not in endPoint or "type" not in endPoint or endPoint["type"] != "mqttTopic" or "mqttClientType" not in endPoint or endPoint["mqttClientType"] != "publisher":
            raise Exception("End point is not as excepted")

        # Finally, we can get the topic to subscribe to
        self.temperatureTopic = endPoint["service"]

        # Now, setup the mqtt client
        self.mqttClient = PahoMQTT.Client("tiot19_Temperature_Receiver", True)
        self.mqttClient.on_connect = self.onConnect
        self.mqttClient.on_message = self.onMessage
        
        try:
            self.mqttClient.connect(self.brokerURL, self.brokerPORT)
            self.mqttClient.subscribe(self.temperatureTopic, 2)
            self.mqttClient.loop_start()
        except:
            raise ConnectionError("Unable to connect to the MQTT message broker")

        # Registration period
        self.period = period
        self.stopThreadEvent = threading.Event()
        self.running = True
        self.subscribeThread = threading.Thread(target = self.subscribeAsService)
        self.subscribePayload = json.dumps(
            {
                "serviceID": "MQTTTemperatureReceiver",
                "description": "An MQTT client that subscribes to the temperature data generated by the Yun board and prints it to the console",
                "endPoints": [{"service": self.temperatureTopic, "type": "mqttTopic", "mqttClientType": "subscriber"}]
            })

    def onConnect(self, client, userdata, flags, rc):
        print("Connected to mqtt broker")

    def onMessage(self, client, userdata, message):
        # Debug
        print(message.payload.decode())

    def run(self, characterToExit: str):
        self.subscribeThread.start()
        print("Waiting for messages [press " + characterToExit + " to exit]")
        
        while True:
            c = input()

            if c == characterToExit:
                break

        # Stop the thread
        self.running = False
        self.stopThreadEvent.set()
        self.subscribeThread.join()

    # Function to run in a separate thread that registers this as a web service to the catalog
    def subscribeAsService(self):
        while self.running:
            # Register to the service catalog
            try:
                response = requests.put(self.catalogURL + ":" + str(self.catalogPORT) + "/addService", data = self.subscribePayload)
                response.raise_for_status()
            except:
                print("Error registering service to catalog")

            self.stopThreadEvent.wait(timeout = self.period)

if __name__ == "__main__":
    try:
        temperatureReceiver = MQTTTemperatureReceiver("http://localhost", 8080, "Yun", 60)
    except Exception as e:
        print(str(e))
        exit(-1)

    temperatureReceiver.run("q")

    print("Exiting...")